### PR TITLE
Resolve build error with RTI Connext DDS 5.3.1

### PR DESCRIPTION
**Pull request by asorbini**
This PR resolves a [compilation error when building `rmw_connextdds` with RTI Connext DDS 5.3.1](https://github.com/ros2/rmw_connextdds/pull/81#issuecomment-1097419848) that was introduced by #81.

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks reasonable to me with green CI.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16567/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11151/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16955/)

**Review by jacobperron — APPROVED** [review]
Thanks, this fixes the issue for me :)
